# Generated by Django 4.2.14 on 2024-08-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='wake_up_time',
        ),
    ]
